<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404222811 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categorie (categorie_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, categorie_libelle VARCHAR(80) NOT NULL, PRIMARY KEY (categorie_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497DD634FB55A9FB ON categorie (categorie_libelle)');
        $this->addSql('CREATE TABLE composer (composer_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, composer_quantite NUMERIC(10, 2) NOT NULL, composer_unite VARCHAR(20) NOT NULL, composer_recette_id INT NOT NULL, composer_ingredient_id INT NOT NULL, PRIMARY KEY (composer_id))');
        $this->addSql('CREATE INDEX IDX_987306D867B3F67C ON composer (composer_recette_id)');
        $this->addSql('CREATE INDEX IDX_987306D83BAB0623 ON composer (composer_ingredient_id)');
        $this->addSql('CREATE TABLE contenir (contenir_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenir_quantite INT NOT NULL, contenir_liste_id INT NOT NULL, contenir_ingredient_id INT NOT NULL, PRIMARY KEY (contenir_id))');
        $this->addSql('CREATE INDEX IDX_3C914DFD29B24D17 ON contenir (contenir_liste_id)');
        $this->addSql('CREATE INDEX IDX_3C914DFDCD226A23 ON contenir (contenir_ingredient_id)');
        $this->addSql('CREATE TABLE etape (etape_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, etape_numero SMALLINT NOT NULL, etape_libelle VARCHAR(150) NOT NULL, etape_description TEXT NOT NULL, etape_duree SMALLINT DEFAULT NULL, recette_id INT NOT NULL, PRIMARY KEY (etape_id))');
        $this->addSql('CREATE INDEX IDX_285F75DD89312FE9 ON etape (recette_id)');
        $this->addSql('CREATE TABLE foyer (foyer_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, foyer_nom VARCHAR(100) NOT NULL, foyer_nombre_pers SMALLINT NOT NULL, foyer_date_creation DATE NOT NULL, PRIMARY KEY (foyer_id))');
        $this->addSql('CREATE TABLE ingredient (ingredient_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ingredient_libelle VARCHAR(100) NOT NULL, ingredient_type VARCHAR(50) DEFAULT NULL, PRIMARY KEY (ingredient_id))');
        $this->addSql('CREATE TABLE "like" (like_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, like_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, like_user_id INT NOT NULL, like_recette_id INT NOT NULL, PRIMARY KEY (like_id))');
        $this->addSql('CREATE INDEX IDX_AC6340B3F4E399B6 ON "like" (like_user_id)');
        $this->addSql('CREATE INDEX IDX_AC6340B32AA58F11 ON "like" (like_recette_id)');
        $this->addSql('CREATE TABLE liste_course (liste_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, liste_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, liste_statut VARCHAR(50) NOT NULL, liste_foyer_id INT NOT NULL, PRIMARY KEY (liste_id))');
        $this->addSql('CREATE INDEX IDX_27EF1A82374CC1A2 ON liste_course (liste_foyer_id)');
        $this->addSql('CREATE TABLE recette (recette_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recette_libelle VARCHAR(150) NOT NULL, recette_description TEXT DEFAULT NULL, recette_difficulte VARCHAR(20) NOT NULL, recette_portion SMALLINT NOT NULL, recette_temps_prepa SMALLINT NOT NULL, recette_temps_cuisson SMALLINT NOT NULL, PRIMARY KEY (recette_id))');
        $this->addSql('CREATE TABLE regime (regime_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, regime_libelle VARCHAR(100) NOT NULL, PRIMARY KEY (regime_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AA864A7C3964383E ON regime (regime_libelle)');
        $this->addSql('CREATE TABLE repas (repas_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, repas_date DATE NOT NULL, repas_type VARCHAR(50) NOT NULL, repas_foyer_id INT NOT NULL, PRIMARY KEY (repas_id))');
        $this->addSql('CREATE INDEX IDX_A8D351B382505A63 ON repas (repas_foyer_id)');
        $this->addSql('CREATE TABLE role (role_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role_libelle VARCHAR(50) NOT NULL, PRIMARY KEY (role_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A181BA2A2 ON role (role_libelle)');
        $this->addSql('CREATE TABLE stocker (stocker_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stocker_quantite_dispo NUMERIC(10, 2) NOT NULL, stocker_foyer_id INT NOT NULL, stocker_ingredient_id INT NOT NULL, PRIMARY KEY (stocker_id))');
        $this->addSql('CREATE INDEX IDX_AD495D96E21271 ON stocker (stocker_foyer_id)');
        $this->addSql('CREATE INDEX IDX_AD495D70DF35D1 ON stocker (stocker_ingredient_id)');
        $this->addSql('CREATE TABLE "user" (user_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_nom VARCHAR(80) NOT NULL, user_prenom VARCHAR(80) NOT NULL, user_mail VARCHAR(150) NOT NULL, user_mdp VARCHAR(255) NOT NULL, user_date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_date_suppression TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_foyer_id INT NOT NULL, user_role_id INT NOT NULL, PRIMARY KEY (user_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6492BA7E081 ON "user" (user_mail)');
        $this->addSql('CREATE INDEX IDX_8D93D649CB1C7E58 ON "user" (user_foyer_id)');
        $this->addSql('CREATE INDEX IDX_8D93D6498E0E3CA6 ON "user" (user_role_id)');
        $this->addSql('CREATE TABLE suivre (user_id INT NOT NULL, regime_id INT NOT NULL, PRIMARY KEY (user_id, regime_id))');
        $this->addSql('CREATE INDEX IDX_3BC593BBA76ED395 ON suivre (user_id)');
        $this->addSql('CREATE INDEX IDX_3BC593BB35E7D534 ON suivre (regime_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE composer ADD CONSTRAINT FK_987306D867B3F67C FOREIGN KEY (composer_recette_id) REFERENCES recette (recette_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE composer ADD CONSTRAINT FK_987306D83BAB0623 FOREIGN KEY (composer_ingredient_id) REFERENCES ingredient (ingredient_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contenir ADD CONSTRAINT FK_3C914DFD29B24D17 FOREIGN KEY (contenir_liste_id) REFERENCES liste_course (liste_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contenir ADD CONSTRAINT FK_3C914DFDCD226A23 FOREIGN KEY (contenir_ingredient_id) REFERENCES ingredient (ingredient_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE etape ADD CONSTRAINT FK_285F75DD89312FE9 FOREIGN KEY (recette_id) REFERENCES recette (recette_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "like" ADD CONSTRAINT FK_AC6340B3F4E399B6 FOREIGN KEY (like_user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "like" ADD CONSTRAINT FK_AC6340B32AA58F11 FOREIGN KEY (like_recette_id) REFERENCES recette (recette_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE liste_course ADD CONSTRAINT FK_27EF1A82374CC1A2 FOREIGN KEY (liste_foyer_id) REFERENCES foyer (foyer_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE repas ADD CONSTRAINT FK_A8D351B382505A63 FOREIGN KEY (repas_foyer_id) REFERENCES foyer (foyer_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stocker ADD CONSTRAINT FK_AD495D96E21271 FOREIGN KEY (stocker_foyer_id) REFERENCES foyer (foyer_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stocker ADD CONSTRAINT FK_AD495D70DF35D1 FOREIGN KEY (stocker_ingredient_id) REFERENCES ingredient (ingredient_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649CB1C7E58 FOREIGN KEY (user_foyer_id) REFERENCES foyer (foyer_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6498E0E3CA6 FOREIGN KEY (user_role_id) REFERENCES role (role_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivre ADD CONSTRAINT FK_3BC593BBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (user_id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE suivre ADD CONSTRAINT FK_3BC593BB35E7D534 FOREIGN KEY (regime_id) REFERENCES regime (regime_id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE composer DROP CONSTRAINT FK_987306D867B3F67C');
        $this->addSql('ALTER TABLE composer DROP CONSTRAINT FK_987306D83BAB0623');
        $this->addSql('ALTER TABLE contenir DROP CONSTRAINT FK_3C914DFD29B24D17');
        $this->addSql('ALTER TABLE contenir DROP CONSTRAINT FK_3C914DFDCD226A23');
        $this->addSql('ALTER TABLE etape DROP CONSTRAINT FK_285F75DD89312FE9');
        $this->addSql('ALTER TABLE "like" DROP CONSTRAINT FK_AC6340B3F4E399B6');
        $this->addSql('ALTER TABLE "like" DROP CONSTRAINT FK_AC6340B32AA58F11');
        $this->addSql('ALTER TABLE liste_course DROP CONSTRAINT FK_27EF1A82374CC1A2');
        $this->addSql('ALTER TABLE repas DROP CONSTRAINT FK_A8D351B382505A63');
        $this->addSql('ALTER TABLE stocker DROP CONSTRAINT FK_AD495D96E21271');
        $this->addSql('ALTER TABLE stocker DROP CONSTRAINT FK_AD495D70DF35D1');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649CB1C7E58');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6498E0E3CA6');
        $this->addSql('ALTER TABLE suivre DROP CONSTRAINT FK_3BC593BBA76ED395');
        $this->addSql('ALTER TABLE suivre DROP CONSTRAINT FK_3BC593BB35E7D534');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE composer');
        $this->addSql('DROP TABLE contenir');
        $this->addSql('DROP TABLE etape');
        $this->addSql('DROP TABLE foyer');
        $this->addSql('DROP TABLE ingredient');
        $this->addSql('DROP TABLE "like"');
        $this->addSql('DROP TABLE liste_course');
        $this->addSql('DROP TABLE recette');
        $this->addSql('DROP TABLE regime');
        $this->addSql('DROP TABLE repas');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE stocker');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE suivre');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
